const { execFileSync } = require("child_process");
const path = require("path");
const fs = require("fs-extra");
const { build } = require("./build");
const { loadConfig } = require("./utils");

function deploy(message) {
const config = loadConfig();
const repoUrl = config.deployTarget;
if (!repoUrl) {
console.error("Please set deployTarget in blog.config.json (your GitHub Pages repo URL)");
process.exit(1);
}

const docsDir = path.join(process.cwd(), "docs");
const deployDir = path.join(process.cwd(), ".deploy");
// Use execFileSync + argument array instead of execSync + string concatenation:
// arguments are passed directly to the child process without going through a shell,
// preventing characters like quotes, $(), ; in repoUrl / commitMsg from being
// interpreted as shell commands (command injection).
// Therefore commitMsg no longer needs manual quote escaping — whatever the user types is committed as-is.
const commitMsg = message || ("deploy: " + new Date().toISOString());

try {
// Step 1: Build
console.log("== Step 1: Rebuild site ==");
build();

// Step 2: Clone/pull the target Pages repo
console.log("== Step 2: Sync GitHub Pages repo ==");
if (!fs.existsSync(path.join(deployDir, ".git"))) {
// First deploy: .deploy may contain a leftover partial clone from a previous interrupted run
// (non-empty but without .git). git clone refuses to clone into a non-empty directory,
// so clear it first; emptyDirSync creates the directory if it doesn't exist.
fs.emptyDirSync(deployDir);
execFileSync("git", ["clone", "--depth", "1", repoUrl, deployDir], { stdio: "inherit" });
} else {
execFileSync("git", ["-C", deployDir, "pull", "--ff-only"], { stdio: "inherit" });
}

// Step 3: Replace Pages repo contents with build output
console.log("== Step 3: Update static files ==");
fs.readdirSync(deployDir).forEach(function (f) {
if (f !== ".git") fs.removeSync(path.join(deployDir, f));
});
fs.copySync(docsDir, deployDir);

// Step 4: Commit and force-push to the Pages repo
// Force push is safe here because the Pages repo contents are entirely generated by the build — no need to preserve history.
console.log("== Step 4: Push to GitHub Pages ==");
var status = execFileSync("git", ["-C", deployDir, "status", "--porcelain"], { encoding: "utf-8" }).trim();
if (status) {
execFileSync("git", ["-C", deployDir, "add", "-A"], { stdio: "inherit" });
execFileSync("git", ["-C", deployDir, "commit", "-m", commitMsg], { stdio: "inherit" });
execFileSync("git", ["-C", deployDir, "push", "--force"], { stdio: "inherit" });
console.log("Pushed to GitHub Pages.");
} else {
console.log("No file changes, skipping push.");
}

console.log("Deploy complete. GitHub Pages usually takes 1-2 minutes to take effect.");
} catch (err) {
console.error("Deploy failed:", err.message);
process.exit(1);
}
}

module.exports = { deploy };
